version: '3.5'

services:
  chat-logs:
    image: starlitghost/desertbot-log:latest
    container_name: chat-logs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:80
    networks:
      - web
    environment:
      - ALLOW_OVERRIDE=true
    volumes:
      - ${LOG_DIR}:/logpath
    labels:
      - "traefik.domain=logs.${DOMAIN_DBCO}"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.backend=chat-logs"
      - "traefik.frontend.rule=Host:logs.${DOMAIN_DBCO}"
      - "traefik.port=80"
      - "traefik.protocol=http"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

networks:
  web:
    external: true

# vim: tabstop=2 shiftwidth=2 expandtab
